# Generated by Django 4.2.2 on 2023-06-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('PCid', models.IntegerField(primary_key=True, serialize=False)),
                ('PCName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('Pprice', models.IntegerField()),
                ('Pdescription', models.TextField()),
                ('Pdate', models.DateField()),
                ('PCName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
